# Site settings
title: HOME                               # 博客的标题
SEOTitle: 陈诚的博客 | Blog                # 显示在浏览器标签上的标题
header-img: img/post-bg-github-cup.jpg       
email: chencheng_199709@163.com
description: "ChenCheng's blog"
keyword: "陈诚的博客, chencheng, java, c++"
url: "http://cent-c.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/cent-c" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "尽吾至而不能至，可以无悔矣。"
sidebar-avatar: /img/chencheng.jpg       # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     chen-cheng-69-5
github_username:    cent-c
jianshu_username:   c53bed4a2a16
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 10c94a3c0dba77813078                            #生成的clientID
  clientSecret: 9d6769c833b5f0a97bcac2c0f4fc60952848939f    #生成的clientSecret
  repo: cent-c.github.io    #仓库名称
  owner: cent-c    #github用户名
  admin: cent-c
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto
ga_domain: auto




# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 3              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "简书",
        href: "http://www.jianshu.com/u/c53bed4a2a16"
    }
]
